# ConfigMap for fhir-sandbox-backend-dev
#
# k8s documentation:
# - https://kubernetes.io/docs/tasks/configure-pod-container/configure-pod-configmap/#create-a-configmap
#
kind: ConfigMap
apiVersion: v1
metadata:
  name: fhir-sandbox-backend-dev
data:
  EXTRA_JAVA_OPTS: -XX:MaxRAMPercentage=75.0
  SERVER_SERVLET_CONTEXTPATH: /fhir-sandbox-backend
  TZ: America/Los_Angeles
  HAPI_FHIR_FHIR_VERSION: R4
  OCTRI_SANDBOX_OAUTH2_AUTHORIZE_ADDRESS: https://octridev.ohsu.edu/fhir-sandbox/oauth2/authorize
  OCTRI_SANDBOX_OAUTH2_ENABLE_TOKEN_AUTH: 'true'
  OCTRI_SANDBOX_OAUTH2_ISSUER_ADDRESS: https://octridev.ohsu.edu/fhir-sandbox
  OCTRI_SANDBOX_OAUTH2_JWK_SET_ADDRESS: https://octridev.ohsu.edu/fhir-sandbox/oauth2/jwks
  OCTRI_SANDBOX_OAUTH2_TOKEN_ADDRESS: https://octridev.ohsu.edu/fhir-sandbox/oauth2/token
  # TODO: move this to a separate ConfigMap if other config files are needed
  application.properties: |
    logging.level.ca.uhn.fhir.interceptor.executor.BaseInterceptorService=off
