---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fhir-sandbox-backend-dev
  labels:
    app: fhir-sandbox-backend-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fhir-sandbox-backend-dev
  template:
    metadata:
      labels:
        app: fhir-sandbox-backend-dev
      annotations:
        co.elastic.logs/multiline.type: pattern
        co.elastic.logs/multiline.pattern: '^[0-9]{4}-[0-9]{2}-[0-9]{2}'
        co.elastic.logs/multiline.negate: 'true'
        co.elastic.logs/multiline.match: after
        co.elastic.logs/processors.dissect.tokenizer: '%{+@timestamp} %{log.level} %{process.pid|long} --- [%{process.thread.name}] %{log.logger} : %{}'
        co.elastic.logs/processors.dissect.ignore_failure: 'true'
        co.elastic.logs/processors.dissect.trim_values: all
        co.elastic.logs/processors.dissect.target_prefix: ''
        co.elastic.logs/processors.dissect.overwrite_keys: 'true'
        prometheus.io/scrape: 'true'
        prometheus.io/path: /fhir-sandbox-backend/actuator/prometheus
        prometheus.io/port: '8080'
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 5333
        runAsGroup: 5333
        fsGroup: 5333
      containers:
      - name: fhir-sandbox-backend
        image: ghcr.io/ohsu-octri/fhir-sandbox-backend:latest
        imagePullPolicy: Always
        securityContext:
          allowPrivilegeEscalation: false
        resources:
          requests:
            memory: 512Mi
            cpu: 50m
          limits:
            memory: 1024Mi
            cpu: 500m
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: fhir-sandbox-backend-dev
        - secretRef:
            name: fhir-sandbox-backend-dev
      imagePullSecrets:
      - name: ghcr-registry-cred
