---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: fhir-sandbox-postgres-dev
spec:
  selector:
    matchLabels:
      app: fhir-sandbox-postgres-dev
  serviceName: fhir-sandbox-postgres-dev
  replicas: 1
  minReadySeconds: 10
  template:
    metadata:
      labels:
        app: fhir-sandbox-postgres-dev
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: postgres
        image: postgres:16
        securityContext:
          allowPrivilegeEscalation: false
        resources:
          requests:
            memory: 512Mi
            cpu: 100m
          limits:
            memory: 2Gi
            cpu: 1000m
        ports:
        - containerPort: 5432
          name: postgres
        env:
        - name: PGDATA
          value: /var/lib/postgresql/data/16/docker
        envFrom:
        - secretRef:
            name: fhir-sandbox-postgres-dev
        livenessProbe:
          exec:
            command:
            - pg_isready
            - -U
            - postgres
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          exec:
            command:
            - pg_isready
            - -U
            - postgres
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
        volumeMounts:
        - name: fhir-sandbox-postgres-dev
          mountPath: /var/lib/postgresql/data
      securityContext:
        # Run as the container's postgres user
        fsGroup: 999
        runAsGroup: 999
        runAsNonRoot: true
        runAsUser: 999
        fsGroupChangePolicy: OnRootMismatch
      imagePullSecrets:
      - name: octri-registry-cred
  volumeClaimTemplates:
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      name: fhir-sandbox-postgres-dev
    spec:
      storageClassName: openebs-hostpath
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 10Gi
---
apiVersion: v1
kind: Service
metadata:
  name: fhir-sandbox-postgres-dev
spec:
  ports:
  - port: 5432
    targetPort: 5432
    protocol: TCP
    name: postgres
  selector:
    app: fhir-sandbox-postgres-dev
