package org.octri.fhir_sandbox_backend.interceptor;

import org.hl7.fhir.r4.model.CapabilityStatement.CapabilityStatementRestComponent;
import org.hl7.fhir.r4.model.CapabilityStatement.CapabilityStatementRestSecurityComponent;
import org.hl7.fhir.r4.model.CapabilityStatement.RestfulCapabilityMode;
import org.hl7.fhir.r4.model.Extension;
import org.hl7.fhir.r4.model.UriType;

import java.util.ArrayList;
import java.util.List;

import org.hl7.fhir.instance.model.api.IBaseConformance;
import org.hl7.fhir.r4.model.CapabilityStatement;

import ca.uhn.fhir.interceptor.api.Hook;
import ca.uhn.fhir.interceptor.api.Interceptor;
import ca.uhn.fhir.interceptor.api.Pointcut;

/**
 * Custom interceptor that adds OAuth endpoint information to the CapabilityStatement generated by the FHIR server.
 */
@Interceptor
public class CapabilityStatementCustomizer {

	private static final String OAUTH_URIS_EXTENSION_URL = "http://fhir-registry.smarthealthit.org/StructureDefinition/oauth-uris";
	private static final String AUTHORIZE_EXTENSION_KEY = "authorize";
	private static final String TOKEN_EXTENSION_KEY = "token";

	private final String authorizeAddress;
	private final String tokenAddress;

	public CapabilityStatementCustomizer(String authorizeAddress, String tokenAddress) {
		this.authorizeAddress = authorizeAddress;
		this.tokenAddress = tokenAddress;
	}

	@Hook(Pointcut.SERVER_CAPABILITY_STATEMENT_GENERATED)
	public void customize(IBaseConformance theCapabilityStatement) {
		CapabilityStatement cs = (CapabilityStatement) theCapabilityStatement;

		CapabilityStatementRestSecurityComponent securityComponent = this.buildSecurityComponent();

		// Get the CapabilityStatementRestComponent for the server if one exists
		List<CapabilityStatementRestComponent> restComponents = cs.getRest();
		CapabilityStatementRestComponent rest = null;
		for (CapabilityStatementRestComponent rc : restComponents) {
			if (rc.getMode().equals(RestfulCapabilityMode.SERVER)) {
				rest = rc;
				break;
			}
		}

		if (rest == null) {
			// Create new rest component
			rest = new CapabilityStatementRestComponent();
			rest.setMode(RestfulCapabilityMode.SERVER);
			rest.setSecurity(securityComponent);
			cs.addRest(rest);
		} else {
			rest.setSecurity(securityComponent);
		}
	}

	private CapabilityStatementRestSecurityComponent buildSecurityComponent() {
		CapabilityStatementRestSecurityComponent securityComponent = new CapabilityStatementRestSecurityComponent();
		Extension oauthExtension = new Extension();

		oauthExtension.setUrl(OAUTH_URIS_EXTENSION_URL);
		List<Extension> extensions = new ArrayList<>();
		extensions.add(new Extension(AUTHORIZE_EXTENSION_KEY, new UriType(this.authorizeAddress)));
		extensions.add(new Extension(TOKEN_EXTENSION_KEY, new UriType(this.tokenAddress)));
		oauthExtension.setExtension(extensions);
		securityComponent.addExtension(oauthExtension);

		return securityComponent;
	}

}
